# Generated by Django 3.0.7 on 2020-06-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0002_auto_20200627_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
