# Generated by Django 3.0.7 on 2020-07-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0003_auto_20200627_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myfinance.Budget'),
            preserve_default=False,
        ),
    ]
