# Generated by Django 3.0.7 on 2020-07-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0005_auto_20200703_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budgeted_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
