# Generated by Django 3.0.7 on 2020-07-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0006_category_budgeted_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategoryAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myfinance.Budget')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myfinance.Category')),
            ],
        ),
    ]
