# Generated by Django 3.0.7 on 2020-07-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0008_auto_20200718_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='category',
            name='budgeted_amt',
        ),
    ]
