# Generated by Django 3.0.7 on 2020-07-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0009_auto_20200718_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategoryamount',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myfinance.Category'),
        ),
    ]
