# Generated by Django 3.0.7 on 2020-07-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0010_auto_20200718_1615'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetcategoryamount',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_category'),
        ),
    ]
