# Generated by Django 3.0.7 on 2020-08-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0015_auto_20200821_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='account_num_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
