# Generated by Django 3.0.7 on 2020-08-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0016_auto_20200829_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='plaid_account_id',
        ),
    ]
