# Generated by Django 3.0.7 on 2020-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0017_auto_20200829_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='plaid_account_id',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
