# Generated by Django 3.0.7 on 2020-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0018_auto_20200829_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_account_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
