# Generated by Django 3.0.7 on 2020-08-29 22:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0019_auto_20200829_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balances',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
