# Generated by Django 3.0.7 on 2020-09-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0021_auto_20200912_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaiditem',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfinance.PlaidItem'),
        ),
        migrations.DeleteModel(
            name='AccountNumber',
        ),
    ]
