# Generated by Django 3.0.7 on 2020-09-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0022_auto_20200912_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfinance.Account'),
        ),
    ]
