# Generated by Django 3.1.4 on 2021-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0024_auto_20201219_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
