# Generated by Django 3.1.4 on 2021-02-20 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0027_transaction_builtin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 20, 8, 30, 52, 64201)),
        ),
    ]
